exclude: ^(\.bumpversion\.cfg|CHANGELOG\.md|site/|webui/dist/|webui/node_modules/)
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-yaml
    exclude: ^mkdocs\.yml$
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: mixed-line-ending
    args: [--fix, lf]
  - id: detect-private-key
  - id: check-toml
  - id: check-json
  - id: pretty-format-json
    args: [--autofix, --indent, '2']
    exclude: ^webui/
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.15.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/sirosen/texthooks
  rev: 0.7.1
  hooks:
  - id: fix-smartquotes
  - id: fix-ligatures
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v3.1.0
  hooks:
  - id: prettier
    types_or: [javascript, jsx, ts, tsx, json, css, markdown]
    files: ^webui/
    additional_dependencies:
    - prettier@3.2.5
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  submodules: false
