<Project>
  <PropertyGroup>
    <Version>6.15.1-1</Version>
    <FileVersion>6.15.1.1</FileVersion>
    <AssemblyVersion>6.15.1.1</AssemblyVersion>
    <Company>Torrentarr</Company>
    <Product>Torrentarr</Product>
    <Copyright>Copyright (c) 2024 Torrentarr Contributors</Copyright>
  </PropertyGroup>
</Project>
