<Project>
  <PropertyGroup>
    <Version>6.14.3</Version>
    <FileVersion>6.14.3</FileVersion>
    <AssemblyVersion>6.14.3.0</AssemblyVersion>
    <Company>Torrentarr</Company>
    <Product>Torrentarr</Product>
    <Copyright>Copyright (c) 2024 Torrentarr Contributors</Copyright>
  </PropertyGroup>
</Project>
