// Generated by Torrentarr.ConfigSchemaGenerator. Do not edit.
export const CONFIG_SCHEMA = {
  "version": 1,
  "sections": {
    "Settings": [
      {
        "section": "Settings",
        "path": [
          "ConfigVersion"
        ],
        "key": "ConfigVersion",
        "label": "Config Version",
        "kind": "text",
        "default": "6.15.2",
        "comments": [
          "Internal config schema version - DO NOT MODIFY",
          "This is managed automatically by qBitrr for config migrations"
        ],
        "required": false,
        "secure": false,
        "uiExpose": false,
        "applyLive": false,
        "requiresRestart": true
      },
      {
        "section": "Settings",
        "path": [
          "ConsoleLevel"
        ],
        "key": "ConsoleLevel",
        "label": "Console Level",
        "kind": "select",
        "default": "INFO",
        "comments": "Level of logging; One of CRITICAL, ERROR, WARNING, NOTICE, INFO, DEBUG, TRACE",
        "required": true,
        "secure": false,
        "uiExpose": true,
        "applyLive": true,
        "requiresRestart": false,
        "options": [
          "CRITICAL",
          "ERROR",
          "WARNING",
          "NOTICE",
          "INFO",
          "DEBUG",
          "TRACE"
        ]
      },
      {
        "section": "Settings",
        "path": [
          "Logging"
        ],
        "key": "Logging",
        "label": "Logging",
        "kind": "checkbox",
        "default": true,
        "comments": "Enable logging to files",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": true
      },
      {
        "section": "Settings",
        "path": [
          "CompletedDownloadFolder"
        ],
        "key": "CompletedDownloadFolder",
        "label": "Completed Download Folder",
        "kind": "text",
        "default": "CHANGE_ME",
        "comments": "Folder where your completed downloads are put into. Can be found in qBitTorrent -\u003E Options -\u003E Downloads -\u003E Default Save Path (Please note, replace all \u0027\\\u0027 with \u0027/\u0027)",
        "required": true,
        "secure": false,
        "uiExpose": true,
        "applyLive": true,
        "requiresRestart": false
      },
      {
        "section": "Settings",
        "path": [
          "FreeSpace"
        ],
        "key": "FreeSpace",
        "label": "Free Space",
        "kind": "text",
        "default": "-1",
        "comments": "The desired amount of free space in the downloads directory [K=kilobytes, M=megabytes, G=gigabytes, T=terabytes] (set to -1 to disable, this bypasses AutoPauseResume)",
        "required": true,
        "secure": false,
        "uiExpose": true,
        "applyLive": true,
        "requiresRestart": false
      },
      {
        "section": "Settings",
        "path": [
          "FreeSpaceFolder"
        ],
        "key": "FreeSpaceFolder",
        "label": "Free Space Folder",
        "kind": "text",
        "default": "CHANGE_ME",
        "comments": "Folder where the free space handler will check for free space (Please note, replace all \u0027\u0027 with \u0027/\u0027)",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": true,
        "requiresRestart": false
      },
      {
        "section": "Settings",
        "path": [
          "AutoPauseResume"
        ],
        "key": "AutoPauseResume",
        "label": "Auto Pause/Resume",
        "kind": "checkbox",
        "default": true,
        "comments": "Enable automation of pausing and resuming torrents as needed (Required enabled for the FreeSpace logic to function)",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": true,
        "requiresRestart": false
      },
      {
        "section": "Settings",
        "path": [
          "NoInternetSleepTimer"
        ],
        "key": "NoInternetSleepTimer",
        "label": "No Internet Sleep",
        "kind": "duration",
        "default": 15,
        "comments": "Time to sleep for if there is no internet (in seconds: 600 = 10 Minutes)",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": true,
        "requiresRestart": false,
        "nativeUnit": "seconds"
      },
      {
        "section": "Settings",
        "path": [
          "LoopSleepTimer"
        ],
        "key": "LoopSleepTimer",
        "label": "Loop Sleep",
        "kind": "duration",
        "default": 5,
        "comments": "Time to sleep between reprocessing torrents (in seconds: 600 = 10 Minutes)",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": true,
        "requiresRestart": false,
        "nativeUnit": "seconds"
      },
      {
        "section": "Settings",
        "path": [
          "SearchLoopDelay"
        ],
        "key": "SearchLoopDelay",
        "label": "Search Loop Delay",
        "kind": "duration",
        "default": -1,
        "comments": "Time to sleep between posting search commands (in seconds: 600 = 10 Minutes)",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": true,
        "requiresRestart": false,
        "nativeUnit": "seconds",
        "allowNegative": true
      },
      {
        "section": "Settings",
        "path": [
          "FailedCategory"
        ],
        "key": "FailedCategory",
        "label": "Failed Category",
        "kind": "text",
        "default": "failed",
        "comments": "Add torrents to this category to mark them as failed",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": true
      },
      {
        "section": "Settings",
        "path": [
          "RecheckCategory"
        ],
        "key": "RecheckCategory",
        "label": "Recheck Category",
        "kind": "text",
        "default": "recheck",
        "comments": "Add torrents to this category to trigger them to be rechecked properly",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": true
      },
      {
        "section": "Settings",
        "path": [
          "Tagless"
        ],
        "key": "Tagless",
        "label": "Tagless",
        "kind": "checkbox",
        "default": false,
        "comments": "Tagless operation",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": true
      },
      {
        "section": "Settings",
        "path": [
          "IgnoreTorrentsYoungerThan"
        ],
        "key": "IgnoreTorrentsYoungerThan",
        "label": "Ignore Torrents Younger Than",
        "kind": "duration",
        "default": 180,
        "comments": [
          "Ignore Torrents which are younger than this value (in seconds: 600 = 10 Minutes)",
          "Only applicable to Re-check and failed categories"
        ],
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": true,
        "requiresRestart": false,
        "nativeUnit": "seconds"
      },
      {
        "section": "Settings",
        "path": [
          "PingURLS"
        ],
        "key": "PingURLS",
        "label": "Ping URLs",
        "kind": "tags",
        "default": [
          "one.one.one.one",
          "dns.google.com"
        ],
        "comments": [
          "URL to be pinged to check if you have a valid internet connection",
          "These will be pinged a **LOT** make sure the service is okay with you sending all the continuous pings."
        ],
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": true,
        "requiresRestart": false,
        "placeholder": "one.one.one.one"
      },
      {
        "section": "Settings",
        "path": [
          "FFprobeAutoUpdate"
        ],
        "key": "FFprobeAutoUpdate",
        "label": "FFprobe Auto Update",
        "kind": "checkbox",
        "default": true,
        "comments": [
          "FFprobe auto updates, binaries are downloaded from https://ffbinaries.com/downloads",
          "If this is disabled and you want ffprobe to work",
          "Ensure that you add the ffprobe binary to the folder\u0022/config/ffprobe.exe\u0022",
          "If no \u0060ffprobe\u0060 binary is found in the folder above all ffprobe functionality will be disabled.",
          "By default this will always be on even if config does not have these key - to disable you need to explicitly set it to \u0060False\u0060"
        ],
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": true,
        "requiresRestart": false
      },
      {
        "section": "Settings",
        "path": [
          "AutoUpdateEnabled"
        ],
        "key": "AutoUpdateEnabled",
        "label": "Auto Update Enabled",
        "kind": "checkbox",
        "default": false,
        "comments": [
          "Automatically attempt to update qBitrr on a schedule",
          "Set to true to enable the auto-update worker."
        ],
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": true,
        "requiresRestart": false
      },
      {
        "section": "Settings",
        "path": [
          "AutoUpdateCron"
        ],
        "key": "AutoUpdateCron",
        "label": "Auto Update Cron",
        "kind": "text",
        "default": "0 3 * * 0",
        "comments": [
          "Cron expression describing when to check for updates",
          "Default is weekly Sunday at 03:00 (0 3 * * 0)."
        ],
        "required": true,
        "secure": false,
        "uiExpose": true,
        "applyLive": true,
        "requiresRestart": false,
        "placeholder": "0 3 * * 0"
      },
      {
        "section": "Settings",
        "path": [
          "AutoUpdateChannel"
        ],
        "key": "AutoUpdateChannel",
        "label": "Auto Update Channel",
        "kind": "select",
        "default": "latest",
        "comments": [
          "Release channel for update checks and auto-updates",
          "latest = newest release (includes build bumps); stable = newest non-build release; nightly = tip of master (unsupported for binary installs)."
        ],
        "required": true,
        "secure": false,
        "uiExpose": true,
        "applyLive": true,
        "requiresRestart": false,
        "options": [
          "latest",
          "stable",
          "nightly"
        ]
      },
      {
        "section": "Settings",
        "path": [
          "AutoRestartProcesses"
        ],
        "key": "AutoRestartProcesses",
        "label": "Auto-Restart Processes",
        "kind": "checkbox",
        "default": true,
        "comments": [
          "Automatically restart worker processes that fail or crash",
          "Set to false to disable auto-restart (processes will only log failures)"
        ],
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": true
      },
      {
        "section": "Settings",
        "path": [
          "MaxProcessRestarts"
        ],
        "key": "MaxProcessRestarts",
        "label": "Max Process Restarts",
        "kind": "number",
        "default": 5,
        "comments": [
          "Maximum number of restart attempts per process within the restart window",
          "Prevents infinite restart loops for processes that crash immediately"
        ],
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": true,
        "minimum": 1
      },
      {
        "section": "Settings",
        "path": [
          "ProcessRestartWindow"
        ],
        "key": "ProcessRestartWindow",
        "label": "Process Restart Window",
        "kind": "duration",
        "default": 300,
        "comments": [
          "Time window (seconds) for tracking restart attempts",
          "If a process restarts MaxProcessRestarts times within this window, auto-restart is disabled for that process"
        ],
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": true,
        "nativeUnit": "seconds"
      },
      {
        "section": "Settings",
        "path": [
          "ProcessRestartDelay"
        ],
        "key": "ProcessRestartDelay",
        "label": "Process Restart Delay",
        "kind": "duration",
        "default": 5,
        "comments": "Delay (seconds) before attempting to restart a failed process",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": true,
        "nativeUnit": "seconds"
      }
    ],
    "WebUI": [
      {
        "section": "WebUI",
        "path": [
          "Host"
        ],
        "key": "Host",
        "label": "WebUI Host",
        "kind": "text",
        "default": "0.0.0.0",
        "comments": "WebUI listen host (default 0.0.0.0; use 127.0.0.1 for localhost-only)",
        "required": true,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": true
      },
      {
        "section": "WebUI",
        "path": [
          "Port"
        ],
        "key": "Port",
        "label": "WebUI Port",
        "kind": "number",
        "default": 6969,
        "comments": "WebUI listen port (default 6969)",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": true,
        "minimum": 1,
        "maximum": 65535
      },
      {
        "section": "WebUI",
        "path": [
          "Token"
        ],
        "key": "Token",
        "label": "WebUI Token",
        "kind": "password",
        "default": "",
        "comments": [
          "Bearer token used when authentication is enabled; does not enable auth by itself.",
          "Available via /api/token and /web/token when authorized (including when AuthDisabled).",
          "Send as Authorization: Bearer \u003Ctoken\u003E on API requests when auth is required."
        ],
        "required": false,
        "secure": true,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": true
      },
      {
        "section": "WebUI",
        "path": [
          "AuthDisabled"
        ],
        "key": "AuthDisabled",
        "label": "Auth Disabled",
        "kind": "checkbox",
        "default": false,
        "comments": [
          "When true, login is not required and the full admin API is open to anyone who can",
          "reach the WebUI port (including token retrieval, config writes, and self-update).",
          "New installs default to false (login required). Legacy configs missing this key",
          "still treat auth as disabled for backward compatibility."
        ],
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": true,
        "description": "Disable login requirement. Opens the full admin API when true (default false for new installs; missing key = disabled for legacy configs)."
      },
      {
        "section": "WebUI",
        "path": [
          "AllowInsecureExposure"
        ],
        "key": "AllowInsecureExposure",
        "label": "Allow Insecure Exposure",
        "kind": "checkbox",
        "default": false,
        "comments": [
          "Required acknowledgment when AuthDisabled is true and Host is 0.0.0.0 or ::.",
          "Set to true only if you intentionally expose an unauthenticated admin WebUI",
          "(e.g. behind a reverse proxy that already authenticates clients).",
          "Legacy configs missing this key keep warn-only behavior; new installs default false."
        ],
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": true,
        "description": "Acknowledge AuthDisabled on a public bind (0.0.0.0/::). Required when both are set; missing key = warn-only for legacy configs."
      },
      {
        "section": "WebUI",
        "path": [
          "AllowInsecureTokenQuery"
        ],
        "key": "AllowInsecureTokenQuery",
        "label": "Allow Insecure Token Query",
        "kind": "checkbox",
        "default": false,
        "comments": [
          "Allow authentication via ?token= query parameter (insecure: leaks in logs/history).",
          "Prefer Authorization: Bearer. Legacy configs missing this key still accept query tokens."
        ],
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": true,
        "description": "Allow ?token= auth (insecure). Prefer Authorization: Bearer header."
      },
      {
        "section": "WebUI",
        "path": [
          "BehindHttpsProxy"
        ],
        "key": "BehindHttpsProxy",
        "label": "Behind HTTPS Proxy",
        "kind": "checkbox",
        "default": false,
        "comments": [
          "Set to true when the WebUI is reached over HTTPS (e.g. behind a reverse proxy).",
          "When true, the app trusts X-Forwarded-Proto and sets the session cookie as Secure.",
          "Leave false for plain HTTP."
        ],
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": true,
        "description": "Set when the WebUI is reached over HTTPS (e.g. reverse proxy). Enables Secure cookies."
      },
      {
        "section": "WebUI",
        "path": [
          "UrlBase"
        ],
        "key": "UrlBase",
        "label": "Url Base",
        "kind": "text",
        "default": "",
        "comments": [
          "Public URL path prefix when served behind a reverse proxy (no trailing slash).",
          "Example: \u0022/qbitrr\u0022 serves the UI at https://host/qbitrr/ui. Leave empty for site root."
        ],
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": true,
        "description": "Public path prefix when behind a reverse proxy (e.g. /qbitrr). Leave empty for site root.",
        "placeholder": "/qbitrr"
      },
      {
        "section": "WebUI",
        "path": [
          "LocalAuthEnabled"
        ],
        "key": "LocalAuthEnabled",
        "label": "Local Auth Enabled",
        "kind": "checkbox",
        "default": false,
        "comments": "Enable username/password login",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": true
      },
      {
        "section": "WebUI",
        "path": [
          "OIDCEnabled"
        ],
        "key": "OIDCEnabled",
        "label": "OIDC Enabled",
        "kind": "checkbox",
        "default": false,
        "comments": "Enable OIDC login",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": true
      },
      {
        "section": "WebUI",
        "path": [
          "Username"
        ],
        "key": "Username",
        "label": "Username",
        "kind": "text",
        "default": "",
        "comments": "Username for local auth",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": false,
        "description": "Username for local auth login"
      },
      {
        "section": "WebUI",
        "path": [
          "PasswordHash"
        ],
        "key": "PasswordHash",
        "label": "Password Hash",
        "kind": "text",
        "default": "",
        "comments": "BCrypt password hash \u2014 set via the WebUI \u0027Set Password\u0027 button, never plain text",
        "required": false,
        "secure": false,
        "uiExpose": false,
        "applyLive": false,
        "requiresRestart": true
      },
      {
        "section": "WebUI",
        "path": [
          "OIDC",
          "Authority"
        ],
        "key": "OIDC.Authority",
        "label": "OIDC Authority",
        "kind": "text",
        "default": "",
        "comments": "OIDC issuer/authority URL (e.g. https://auth.example.com/application/o/qbitrr)",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": true
      },
      {
        "section": "WebUI",
        "path": [
          "OIDC",
          "ClientId"
        ],
        "key": "OIDC.ClientId",
        "label": "OIDC Client ID",
        "kind": "text",
        "default": "",
        "comments": "OAuth2 client ID",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": true
      },
      {
        "section": "WebUI",
        "path": [
          "OIDC",
          "ClientSecret"
        ],
        "key": "OIDC.ClientSecret",
        "label": "OIDC Client Secret",
        "kind": "password",
        "default": "",
        "comments": "OAuth2 client secret",
        "required": false,
        "secure": true,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": true
      },
      {
        "section": "WebUI",
        "path": [
          "OIDC",
          "Scopes"
        ],
        "key": "OIDC.Scopes",
        "label": "OIDC Scopes",
        "kind": "text",
        "default": "openid profile",
        "comments": "Space-separated OIDC scopes",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": true
      },
      {
        "section": "WebUI",
        "path": [
          "OIDC",
          "CallbackPath"
        ],
        "key": "OIDC.CallbackPath",
        "label": "OIDC Callback Path",
        "kind": "text",
        "default": "/signin-oidc",
        "comments": "OIDC callback path (must match IdP redirect URI)",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": true
      },
      {
        "section": "WebUI",
        "path": [
          "OIDC",
          "RequireHttpsMetadata"
        ],
        "key": "OIDC.RequireHttpsMetadata",
        "label": "OIDC Require HTTPS Metadata",
        "kind": "checkbox",
        "default": true,
        "comments": "Require HTTPS for IdP metadata (set false only for local dev OIDC)",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": true
      },
      {
        "section": "WebUI",
        "path": [
          "LiveArr"
        ],
        "key": "LiveArr",
        "label": "Live",
        "kind": "checkbox",
        "default": true,
        "comments": "Enable live updates for Arr catalogs and the qBittorrent overview",
        "required": false,
        "secure": false,
        "uiExpose": false,
        "applyLive": true,
        "requiresRestart": false
      },
      {
        "section": "WebUI",
        "path": [
          "Theme"
        ],
        "key": "Theme",
        "label": "Theme",
        "kind": "select",
        "default": "Dark",
        "comments": "WebUI theme (Light or Dark)",
        "required": false,
        "secure": false,
        "uiExpose": false,
        "applyLive": true,
        "requiresRestart": false,
        "options": [
          "Light",
          "Dark"
        ]
      },
      {
        "section": "WebUI",
        "path": [
          "ViewDensity"
        ],
        "key": "ViewDensity",
        "label": "View Density",
        "kind": "select",
        "default": "Comfortable",
        "comments": "WebUI view density (Comfortable or Compact)",
        "required": false,
        "secure": false,
        "uiExpose": false,
        "applyLive": true,
        "requiresRestart": false,
        "options": [
          "Comfortable",
          "Compact"
        ]
      }
    ],
    "qBit": [
      {
        "section": "qBit",
        "path": [
          "Disabled"
        ],
        "key": "Disabled",
        "label": "Disabled",
        "kind": "checkbox",
        "default": false,
        "comments": [
          "Skip connecting this qBit instance while keeping the section in config.",
          "Does not enable global headless mode; omit all [qBit] / [qBit-*] sections (or use QBITRR_QBIT_DISABLED / SEARCH_ONLY) for search-only without torrent management."
        ],
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": false
      },
      {
        "section": "qBit",
        "path": [
          "Host"
        ],
        "key": "Host",
        "label": "Host",
        "kind": "text",
        "default": "CHANGE_ME",
        "comments": "qbittorrent WebUI URL/IP - Can be found in Options \u003E Web UI (called \u0022IP Address\u0022)",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": false
      },
      {
        "section": "qBit",
        "path": [
          "Port"
        ],
        "key": "Port",
        "label": "Port",
        "kind": "number",
        "default": 8080,
        "comments": "qbittorrent WebUI Port - Can be found in Options \u003E Web UI (called \u0022Port\u0022 on top right corner of the window)",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": false,
        "minimum": 1,
        "maximum": 65535
      },
      {
        "section": "qBit",
        "path": [
          "UserName"
        ],
        "key": "UserName",
        "label": "UserName",
        "kind": "text",
        "default": "CHANGE_ME",
        "comments": "qbittorrent WebUI Authentication - Can be found in Options \u003E Web UI \u003E Authentication",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": false
      },
      {
        "section": "qBit",
        "path": [
          "Password"
        ],
        "key": "Password",
        "label": "Password",
        "kind": "password",
        "default": "CHANGE_ME",
        "comments": "If you set \u0022Bypass authentication on localhost or whitelisted IPs\u0022 remove this field.",
        "required": false,
        "secure": true,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": false
      },
      {
        "section": "qBit",
        "path": [
          "SkipTLSVerify"
        ],
        "key": "SkipTLSVerify",
        "label": "Skip TLS Verify",
        "kind": "checkbox",
        "default": false,
        "comments": [
          "If true, do not verify TLS certificates for HTTPS WebUI (self-signed certs). Disables MITM protection for that connection."
        ],
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": false
      },
      {
        "section": "qBit",
        "path": [
          "ManagedCategories"
        ],
        "key": "ManagedCategories",
        "label": "Managed Categories",
        "kind": "tags",
        "default": [],
        "comments": [
          "Categories managed directly by this qBit instance (not managed by Arr instances).",
          "These categories will have seeding settings applied according to CategorySeeding configuration.",
          "Subcategory paths use \u0027/\u0027 to match qBittorrent (for example \u0027seed/tleech\u0027).",
          "Example: [\u0027downloads\u0027, \u0027private-tracker\u0027, \u0027long-term-seed\u0027]"
        ],
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": false
      },
      {
        "section": "qBit",
        "path": [
          "MatchSubcategories"
        ],
        "key": "MatchSubcategories",
        "label": "Match Subcategories",
        "kind": "checkbox",
        "default": false,
        "comments": [
          "When true, configured categories ALSO match torrents in any subcategory beneath them.",
          "Example: setting MatchSubcategories=true with ManagedCategories=[\u0027seed\u0027] manages",
          "torrents whose qBit category is \u0027seed\u0027, \u0027seed/tleech\u0027, \u0027seed/longterm\u0027, etc.",
          "When false (default) the qBit category string must match exactly."
        ],
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": false
      },
      {
        "section": "qBit",
        "path": [
          "CategorySeeding",
          "DownloadRateLimitPerTorrent"
        ],
        "key": "CategorySeeding.DownloadRateLimitPerTorrent",
        "label": "Download Rate Limit Per Torrent",
        "kind": "number",
        "default": -1,
        "comments": "Download rate limit per torrent in KB/s (-1 = disabled)",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": false,
        "allowNegative": true
      },
      {
        "section": "qBit",
        "path": [
          "CategorySeeding",
          "UploadRateLimitPerTorrent"
        ],
        "key": "CategorySeeding.UploadRateLimitPerTorrent",
        "label": "Upload Rate Limit Per Torrent",
        "kind": "number",
        "default": -1,
        "comments": "Upload rate limit per torrent in KB/s (-1 = disabled)",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": false,
        "allowNegative": true
      },
      {
        "section": "qBit",
        "path": [
          "CategorySeeding",
          "MaxUploadRatio"
        ],
        "key": "CategorySeeding.MaxUploadRatio",
        "label": "Max Upload Ratio",
        "kind": "number",
        "default": -1,
        "comments": "Maximum upload ratio (-1 = disabled, e.g. 2.0 for 200%)",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": false,
        "allowNegative": true
      },
      {
        "section": "qBit",
        "path": [
          "CategorySeeding",
          "MaxSeedingTime"
        ],
        "key": "CategorySeeding.MaxSeedingTime",
        "label": "Max Seeding Time",
        "kind": "duration",
        "default": -1,
        "comments": "Maximum seeding time in seconds (-1 = disabled, e.g. 604800 for 7 days)",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": false,
        "nativeUnit": "seconds",
        "allowNegative": true
      },
      {
        "section": "qBit",
        "path": [
          "CategorySeeding",
          "RemoveTorrent"
        ],
        "key": "CategorySeeding.RemoveTorrent",
        "label": "Remove Torrent",
        "kind": "select",
        "default": -1,
        "comments": [
          "When to remove torrents from qBittorrent:",
          "  -1 = Never remove",
          "   1 = Remove when MaxUploadRatio is reached",
          "   2 = Remove when MaxSeedingTime is reached",
          "   3 = Remove when either condition is met (OR)",
          "   4 = Remove when both conditions are met (AND)"
        ],
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": false,
        "options": [
          "-1",
          "1",
          "2",
          "3",
          "4"
        ]
      },
      {
        "section": "qBit",
        "path": [
          "CategorySeeding",
          "HitAndRunMode"
        ],
        "key": "CategorySeeding.HitAndRunMode",
        "label": "Hit and Run Mode",
        "kind": "select",
        "default": "disabled",
        "comments": [
          "Hit and Run mode: and = require both ratio and time; or = either clears; disabled = no HnR."
        ],
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": false,
        "options": [
          "disabled",
          "and",
          "or"
        ]
      },
      {
        "section": "qBit",
        "path": [
          "CategorySeeding",
          "MinSeedRatio"
        ],
        "key": "CategorySeeding.MinSeedRatio",
        "label": "Min Seed Ratio",
        "kind": "number",
        "default": 1,
        "comments": "Minimum seed ratio before removal allowed (HnR protection)",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": false
      },
      {
        "section": "qBit",
        "path": [
          "CategorySeeding",
          "MinSeedingTimeDays"
        ],
        "key": "CategorySeeding.MinSeedingTimeDays",
        "label": "Min Seeding Time Days",
        "kind": "number",
        "default": 0,
        "comments": "Minimum seeding time in days before removal allowed (HnR protection, 0 = ratio only)",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": false
      },
      {
        "section": "qBit",
        "path": [
          "CategorySeeding",
          "HitAndRunMinimumDownloadPercent"
        ],
        "key": "CategorySeeding.HitAndRunMinimumDownloadPercent",
        "label": "Hit and Run Minimum Download Percent",
        "kind": "number",
        "default": 10,
        "comments": "Minimum download percentage before a torrent is considered for HnR (0-100, default 10)",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": false,
        "minimum": 0,
        "maximum": 100
      },
      {
        "section": "qBit",
        "path": [
          "CategorySeeding",
          "HitAndRunPartialSeedRatio"
        ],
        "key": "CategorySeeding.HitAndRunPartialSeedRatio",
        "label": "Hit and Run Partial Seed Ratio",
        "kind": "number",
        "default": 1,
        "comments": "Minimum ratio for partial downloads (\u003E=HitAndRunMinimumDownloadPercent% but \u003C100% complete)",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": false
      },
      {
        "section": "qBit",
        "path": [
          "CategorySeeding",
          "TrackerUpdateBuffer"
        ],
        "key": "CategorySeeding.TrackerUpdateBuffer",
        "label": "Tracker Update Buffer",
        "kind": "duration",
        "default": 0,
        "comments": "Extra seconds buffer for tracker stats lag (0 = disabled)",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": false,
        "nativeUnit": "seconds"
      },
      {
        "section": "qBit",
        "path": [
          "CategorySeeding",
          "StalledDelay"
        ],
        "key": "CategorySeeding.StalledDelay",
        "label": "Stalled Delay",
        "kind": "duration",
        "default": -1,
        "comments": "Stalled cleanup grace period in minutes (-1 = infinite, 0 = immediate cleanup).",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": false,
        "nativeUnit": "minutes",
        "allowNegative": true
      },
      {
        "section": "qBit",
        "path": [
          "CategorySeeding",
          "IgnoreTorrentsYoungerThan"
        ],
        "key": "CategorySeeding.IgnoreTorrentsYoungerThan",
        "label": "Ignore Torrents Younger Than",
        "kind": "duration",
        "default": 180,
        "comments": "Ignore torrents younger than this (seconds). Stalled removal also requires last_activity older than this.",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": false,
        "requiresRestart": false,
        "nativeUnit": "seconds"
      }
    ],
    "Arr": [
      {
        "section": "Arr",
        "path": [
          "Managed"
        ],
        "key": "Managed",
        "label": "Managed",
        "kind": "checkbox",
        "default": true,
        "comments": "Toggle whether to manage the Servarr instance torrents.",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null
      },
      {
        "section": "Arr",
        "path": [
          "URI"
        ],
        "key": "URI",
        "label": "URI",
        "kind": "text",
        "default": "CHANGE_ME",
        "comments": "The URL used to access Servarr interface eg. http://ip:port(if you use a domain enter the domain without a port)",
        "required": true,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null
      },
      {
        "section": "Arr",
        "path": [
          "APIKey"
        ],
        "key": "APIKey",
        "label": "API Key",
        "kind": "password",
        "default": "CHANGE_ME",
        "comments": "The Servarr API Key, Can be found it Settings \u003E General \u003E Security",
        "required": true,
        "secure": true,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null
      },
      {
        "section": "Arr",
        "path": [
          "SkipTLSVerify"
        ],
        "key": "SkipTLSVerify",
        "label": "Skip TLS Verify",
        "kind": "checkbox",
        "default": false,
        "comments": [
          "If true, do not verify TLS for this Servarr API (HTTPS). Does not affect Overseerr/Ombi.",
          "Disables MITM protection for that connection."
        ],
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null
      },
      {
        "section": "Arr",
        "path": [
          "Category"
        ],
        "key": "Category",
        "label": "Category",
        "kind": "text",
        "default": "CHANGE_ME",
        "comments": "Category applied by Servarr to torrents in qBitTorrent, can be found in Settings \u003E Download Clients \u003E qBit \u003E Category",
        "required": true,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null
      },
      {
        "section": "Arr",
        "path": [
          "ReSearch"
        ],
        "key": "ReSearch",
        "label": "Re-search",
        "kind": "checkbox",
        "default": true,
        "comments": "Toggle whether to send a query to Servarr to search any failed torrents",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null
      },
      {
        "section": "Arr",
        "path": [
          "importMode"
        ],
        "key": "importMode",
        "label": "Import Mode",
        "kind": "select",
        "default": "Auto",
        "comments": "The Servarr\u0027s Import Mode(one of Move, Copy or Auto)",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null,
        "options": [
          "Move",
          "Copy",
          "Auto"
        ]
      },
      {
        "section": "Arr",
        "path": [
          "RssSyncTimer"
        ],
        "key": "RssSyncTimer",
        "label": "RSS Sync Timer",
        "kind": "duration",
        "default": 1,
        "comments": "Timer to call RSSSync (In minutes) - Set to 0 to disable (Values below 5 can cause errors for maximum retires)",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null,
        "nativeUnit": "minutes"
      },
      {
        "section": "Arr",
        "path": [
          "RefreshDownloadsTimer"
        ],
        "key": "RefreshDownloadsTimer",
        "label": "Refresh Downloads Timer",
        "kind": "duration",
        "default": 1,
        "comments": "Timer to call RefreshDownloads to update the queue. (In minutes) - Set to 0 to disable (Values below 5 can cause errors for maximum retires)",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null,
        "nativeUnit": "minutes"
      },
      {
        "section": "Arr",
        "path": [
          "ArrErrorCodesToBlocklist"
        ],
        "key": "ArrErrorCodesToBlocklist",
        "label": "Arr Error Codes To Blocklist",
        "kind": "tags",
        "default": [],
        "comments": [
          "Error messages shown my the Arr instance which should be considered failures.",
          "This entry should be a list, leave it empty if you want to disable this error handling.",
          "If enabled qBitrr will remove the failed files and tell the Arr instance the download failed"
        ],
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null
      },
      {
        "section": "Arr",
        "path": [
          "EntrySearch",
          "SearchMissing"
        ],
        "key": "EntrySearch.SearchMissing",
        "label": "Search Missing",
        "kind": "checkbox",
        "default": true,
        "comments": "Should search for Missing files?",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null
      },
      {
        "section": "Arr",
        "path": [
          "EntrySearch",
          "AlsoSearchSpecials"
        ],
        "key": "EntrySearch.AlsoSearchSpecials",
        "label": "Also Search Specials",
        "kind": "checkbox",
        "default": false,
        "comments": "Should search for specials episodes? (Season 00)",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null,
        "arrKinds": [
          "sonarr"
        ]
      },
      {
        "section": "Arr",
        "path": [
          "EntrySearch",
          "Unmonitored"
        ],
        "key": "EntrySearch.Unmonitored",
        "label": "Unmonitored",
        "kind": "checkbox",
        "default": false,
        "comments": "Should search for unmonitored media?",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null,
        "arrKinds": [
          "radarr",
          "readarr",
          "sonarr"
        ]
      },
      {
        "section": "Arr",
        "path": [
          "EntrySearch",
          "SearchLimit"
        ],
        "key": "EntrySearch.SearchLimit",
        "label": "Search Limit",
        "kind": "number",
        "default": 5,
        "comments": "Maximum allowed Searches at any one point",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null,
        "arrKinds": [
          "radarr",
          "readarr",
          "sonarr"
        ]
      },
      {
        "section": "Arr",
        "path": [
          "EntrySearch",
          "SearchByYear"
        ],
        "key": "EntrySearch.SearchByYear",
        "label": "Search By Year",
        "kind": "checkbox",
        "default": true,
        "comments": "Order searches by year",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null,
        "arrKinds": [
          "radarr",
          "readarr",
          "sonarr"
        ]
      },
      {
        "section": "Arr",
        "path": [
          "EntrySearch",
          "SearchInReverse"
        ],
        "key": "EntrySearch.SearchInReverse",
        "label": "Search In Reverse",
        "kind": "checkbox",
        "default": false,
        "comments": "Reverse search order (Start searching oldest to newest)",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null
      },
      {
        "section": "Arr",
        "path": [
          "EntrySearch",
          "SearchRequestsEvery"
        ],
        "key": "EntrySearch.SearchRequestsEvery",
        "label": "Search Requests Every",
        "kind": "duration",
        "default": 300,
        "comments": "Delay (in seconds) between checking for new Overseerr/Ombi requests (Radarr/Sonarr only). Does NOT affect delay between individual search commands (use Settings.SearchLoopDelay for that).",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null,
        "nativeUnit": "seconds",
        "arrKinds": [
          "radarr",
          "sonarr"
        ]
      },
      {
        "section": "Arr",
        "path": [
          "EntrySearch",
          "DoUpgradeSearch"
        ],
        "key": "EntrySearch.DoUpgradeSearch",
        "label": "Do Upgrade Search",
        "kind": "checkbox",
        "default": false,
        "comments": "Search media which already have a file in hopes of finding a better quality version.",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null
      },
      {
        "section": "Arr",
        "path": [
          "EntrySearch",
          "QualityUnmetSearch"
        ],
        "key": "EntrySearch.QualityUnmetSearch",
        "label": "Quality Unmet Search",
        "kind": "checkbox",
        "default": false,
        "comments": "Do a quality unmet search for existing entries.",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null
      },
      {
        "section": "Arr",
        "path": [
          "EntrySearch",
          "CustomFormatUnmetSearch"
        ],
        "key": "EntrySearch.CustomFormatUnmetSearch",
        "label": "Custom Format Unmet Search",
        "kind": "checkbox",
        "default": false,
        "comments": "Do a minimum custom format score unmet search for existing entries.",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null
      },
      {
        "section": "Arr",
        "path": [
          "EntrySearch",
          "ForceMinimumCustomFormat"
        ],
        "key": "EntrySearch.ForceMinimumCustomFormat",
        "label": "Force Minimum Custom Format",
        "kind": "checkbox",
        "default": false,
        "comments": "Automatically remove torrents that do not mee the minimum custom format score.",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null
      },
      {
        "section": "Arr",
        "path": [
          "EntrySearch",
          "SearchAgainOnSearchCompletion"
        ],
        "key": "EntrySearch.SearchAgainOnSearchCompletion",
        "label": "Search Again On Search Completion",
        "kind": "checkbox",
        "default": true,
        "comments": "Once you have search all files on your specified year range restart the loop and search again.",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null
      },
      {
        "section": "Arr",
        "path": [
          "EntrySearch",
          "UseTempForMissing"
        ],
        "key": "EntrySearch.UseTempForMissing",
        "label": "Use Temp For Missing",
        "kind": "checkbox",
        "default": false,
        "comments": "Use Temp profile for missing",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null
      },
      {
        "section": "Arr",
        "path": [
          "EntrySearch",
          "KeepTempProfile"
        ],
        "key": "EntrySearch.KeepTempProfile",
        "label": "Keep Temp Profile",
        "kind": "checkbox",
        "default": false,
        "comments": "Don\u0027t change back to main profile",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null
      },
      {
        "section": "Arr",
        "path": [
          "EntrySearch",
          "QualityProfileMappings"
        ],
        "key": "EntrySearch.QualityProfileMappings",
        "label": "Quality Profile Mappings",
        "kind": "mapping",
        "default": {},
        "comments": [
          "Quality profile mappings for temp profile switching (Main Profile Name -\u003E Temp Profile Name)",
          "Profile names must match exactly as they appear in your Arr instance",
          "Example: QualityProfileMappings = {\u0022HD-1080p\u0022 = \u0022SD\u0022, \u0022HD-720p\u0022 = \u0022SD\u0022}"
        ],
        "required": false,
        "secure": false,
        "uiExpose": false,
        "applyLive": null,
        "requiresRestart": null
      },
      {
        "section": "Arr",
        "path": [
          "EntrySearch",
          "ForceResetTempProfiles"
        ],
        "key": "EntrySearch.ForceResetTempProfiles",
        "label": "Force Reset Temp Profiles",
        "kind": "checkbox",
        "default": false,
        "comments": "Reset all items using temp profiles to their original main profile on qBitrr startup",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null
      },
      {
        "section": "Arr",
        "path": [
          "EntrySearch",
          "TempProfileResetTimeoutMinutes"
        ],
        "key": "EntrySearch.TempProfileResetTimeoutMinutes",
        "label": "Temp Profile Reset Timeout Minutes",
        "kind": "number",
        "default": 0,
        "comments": "Timeout in minutes after which items with temp profiles are automatically reset to main profile (0 = disabled)",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null
      },
      {
        "section": "Arr",
        "path": [
          "EntrySearch",
          "ProfileSwitchRetryAttempts"
        ],
        "key": "EntrySearch.ProfileSwitchRetryAttempts",
        "label": "Profile Switch Retry Attempts",
        "kind": "number",
        "default": 3,
        "comments": "Number of retry attempts for profile switch API calls (default: 3)",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null
      },
      {
        "section": "Arr",
        "path": [
          "EntrySearch",
          "SearchBySeries"
        ],
        "key": "EntrySearch.SearchBySeries",
        "label": "Search By Series",
        "kind": "select",
        "default": "smart",
        "comments": [
          "Search mode: true (always series search), false (always episode search), or \u0027smart\u0027 (automatic)",
          "Smart mode: uses series search for entire seasons/series, episode search for single episodes",
          "(Series search ignores QualityUnmetSearch and CustomFormatUnmetSearch settings)"
        ],
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null,
        "options": [
          "smart",
          "true",
          "false"
        ],
        "arrKinds": [
          "sonarr"
        ]
      },
      {
        "section": "Arr",
        "path": [
          "EntrySearch",
          "PrioritizeTodaysReleases"
        ],
        "key": "EntrySearch.PrioritizeTodaysReleases",
        "label": "Prioritize Todays Releases",
        "kind": "checkbox",
        "default": true,
        "comments": "Prioritize Today\u0027s releases (Similar effect as RSS Sync, where it searches today\u0027s release episodes first, only works on Sonarr).",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null,
        "arrKinds": [
          "sonarr"
        ]
      },
      {
        "section": "Arr",
        "path": [
          "EntrySearch",
          "Ombi",
          "SearchOmbiRequests"
        ],
        "key": "EntrySearch.Ombi.SearchOmbiRequests",
        "label": "Search Ombi Requests",
        "kind": "checkbox",
        "default": false,
        "comments": "Search Ombi for pending requests (Will only work if \u0027SearchMissing\u0027 is enabled.)",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null,
        "arrKinds": [
          "radarr",
          "sonarr"
        ]
      },
      {
        "section": "Arr",
        "path": [
          "EntrySearch",
          "Ombi",
          "OmbiURI"
        ],
        "key": "EntrySearch.Ombi.OmbiURI",
        "label": "Ombi URI",
        "kind": "text",
        "default": "CHANGE_ME",
        "comments": "Ombi URI eg. http://ip:port (Note that this has to be the instance of Ombi which manage the Arr instance request (If you have multiple Ombi instances)",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null,
        "arrKinds": [
          "radarr",
          "sonarr"
        ]
      },
      {
        "section": "Arr",
        "path": [
          "EntrySearch",
          "Ombi",
          "OmbiAPIKey"
        ],
        "key": "EntrySearch.Ombi.OmbiAPIKey",
        "label": "Ombi API Key",
        "kind": "password",
        "default": "CHANGE_ME",
        "comments": "Ombi\u0027s API Key",
        "required": false,
        "secure": true,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null,
        "arrKinds": [
          "radarr",
          "sonarr"
        ]
      },
      {
        "section": "Arr",
        "path": [
          "EntrySearch",
          "Ombi",
          "ApprovedOnly"
        ],
        "key": "EntrySearch.Ombi.ApprovedOnly",
        "label": "Ombi Approved Only",
        "kind": "checkbox",
        "default": true,
        "comments": "Only process approved requests",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null,
        "arrKinds": [
          "radarr",
          "sonarr"
        ]
      },
      {
        "section": "Arr",
        "path": [
          "EntrySearch",
          "Ombi",
          "SkipTLSVerify"
        ],
        "key": "EntrySearch.Ombi.SkipTLSVerify",
        "label": "Ombi Skip TLS Verify",
        "kind": "checkbox",
        "default": false,
        "comments": [
          "If true, do not verify TLS for Ombi HTTPS (self-signed). Disables MITM protection."
        ],
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null,
        "arrKinds": [
          "radarr",
          "sonarr"
        ]
      },
      {
        "section": "Arr",
        "path": [
          "EntrySearch",
          "Overseerr",
          "SearchOverseerrRequests"
        ],
        "key": "EntrySearch.Overseerr.SearchOverseerrRequests",
        "label": "Search Overseerr Requests",
        "kind": "checkbox",
        "default": false,
        "comments": [
          "Search Overseerr for pending requests (Will only work if \u0027SearchMissing\u0027 is enabled.)",
          "If this and Ombi are both enable, Ombi will be ignored"
        ],
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null,
        "arrKinds": [
          "radarr",
          "sonarr"
        ]
      },
      {
        "section": "Arr",
        "path": [
          "EntrySearch",
          "Overseerr",
          "OverseerrURI"
        ],
        "key": "EntrySearch.Overseerr.OverseerrURI",
        "label": "Overseerr URI",
        "kind": "text",
        "default": "CHANGE_ME",
        "comments": "Overseerr\u0027s URI eg. http://ip:port",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null,
        "arrKinds": [
          "radarr",
          "sonarr"
        ]
      },
      {
        "section": "Arr",
        "path": [
          "EntrySearch",
          "Overseerr",
          "OverseerrAPIKey"
        ],
        "key": "EntrySearch.Overseerr.OverseerrAPIKey",
        "label": "Overseerr API Key",
        "kind": "password",
        "default": "CHANGE_ME",
        "comments": "Overseerr\u0027s API Key",
        "required": false,
        "secure": true,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null,
        "arrKinds": [
          "radarr",
          "sonarr"
        ]
      },
      {
        "section": "Arr",
        "path": [
          "EntrySearch",
          "Overseerr",
          "ApprovedOnly"
        ],
        "key": "EntrySearch.Overseerr.ApprovedOnly",
        "label": "Overseerr Approved Only",
        "kind": "checkbox",
        "default": true,
        "comments": "Only process approved requests",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null,
        "arrKinds": [
          "radarr",
          "sonarr"
        ]
      },
      {
        "section": "Arr",
        "path": [
          "EntrySearch",
          "Overseerr",
          "SkipTLSVerify"
        ],
        "key": "EntrySearch.Overseerr.SkipTLSVerify",
        "label": "Overseerr Skip TLS Verify",
        "kind": "checkbox",
        "default": false,
        "comments": [
          "If true, do not verify TLS for Overseerr HTTPS (self-signed). Disables MITM protection."
        ],
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null,
        "arrKinds": [
          "radarr",
          "sonarr"
        ]
      },
      {
        "section": "Arr",
        "path": [
          "EntrySearch",
          "Overseerr",
          "Is4K"
        ],
        "key": "EntrySearch.Overseerr.Is4K",
        "label": "Is 4K",
        "kind": "checkbox",
        "default": false,
        "comments": "Only for 4K Instances",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null,
        "arrKinds": [
          "radarr",
          "sonarr"
        ]
      },
      {
        "section": "Arr",
        "path": [
          "Torrent",
          "CaseSensitiveMatches"
        ],
        "key": "Torrent.CaseSensitiveMatches",
        "label": "Case Sensitive Matches",
        "kind": "checkbox",
        "default": false,
        "comments": "Set it to regex matches to respect/ignore case.",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null
      },
      {
        "section": "Arr",
        "path": [
          "Torrent",
          "FolderExclusionRegex"
        ],
        "key": "Torrent.FolderExclusionRegex",
        "label": "Folder Exclusion Regex",
        "kind": "tags",
        "default": [],
        "comments": [
          "These regex values will match any folder where the full name matches the specified values here, comma separated strings.",
          "These regex need to be escaped, that\u0027s why you see so many backslashes."
        ],
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null
      },
      {
        "section": "Arr",
        "path": [
          "Torrent",
          "FileNameExclusionRegex"
        ],
        "key": "Torrent.FileNameExclusionRegex",
        "label": "File Name Exclusion Regex",
        "kind": "tags",
        "default": [],
        "comments": [
          "These regex values will match any folder where the full name matches the specified values here, comma separated strings.",
          "These regex need to be escaped, that\u0027s why you see so many backslashes."
        ],
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null
      },
      {
        "section": "Arr",
        "path": [
          "Torrent",
          "FileExtensionAllowlist"
        ],
        "key": "Torrent.FileExtensionAllowlist",
        "label": "File Extension Allowlist",
        "kind": "tags",
        "default": [],
        "comments": "Only files with these extensions will be allowed to be downloaded, comma separated strings or regex, leave it empty to allow all extensions",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null
      },
      {
        "section": "Arr",
        "path": [
          "Torrent",
          "AutoDelete"
        ],
        "key": "Torrent.AutoDelete",
        "label": "Auto Delete",
        "kind": "checkbox",
        "default": false,
        "comments": "Auto delete files that can\u0027t be playable (i.e .exe, .png)",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null
      },
      {
        "section": "Arr",
        "path": [
          "Torrent",
          "IgnoreTorrentsYoungerThan"
        ],
        "key": "Torrent.IgnoreTorrentsYoungerThan",
        "label": "Ignore Torrents Younger Than",
        "kind": "duration",
        "default": 180,
        "comments": "Ignore Torrents which are younger than this value (in seconds: 600 = 10 Minutes)",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null,
        "nativeUnit": "seconds"
      },
      {
        "section": "Arr",
        "path": [
          "Torrent",
          "MaximumETA"
        ],
        "key": "Torrent.MaximumETA",
        "label": "Maximum ETA",
        "kind": "duration",
        "default": -1,
        "comments": [
          "Maximum allowed remaining ETA for torrent completion (in seconds: 3600 = 1 Hour)",
          "A positive tracker MaximumETA overrides this value; tracker -1/unset does not clear this limit",
          "Unlimited only when neither this setting nor a matched tracker sets a positive MaximumETA"
        ],
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null,
        "nativeUnit": "seconds",
        "allowNegative": true
      },
      {
        "section": "Arr",
        "path": [
          "Torrent",
          "MaximumDeletablePercentage"
        ],
        "key": "Torrent.MaximumDeletablePercentage",
        "label": "Maximum Deletable Percentage",
        "kind": "number",
        "default": 0.99,
        "comments": "Do not delete torrents with higher completion percentage than this setting (0.5 = 50%, 1.0 = 100%)",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null,
        "minimum": 0,
        "maximum": 1
      },
      {
        "section": "Arr",
        "path": [
          "Torrent",
          "DoNotRemoveSlow"
        ],
        "key": "Torrent.DoNotRemoveSlow",
        "label": "Do Not Remove Slow",
        "kind": "checkbox",
        "default": true,
        "comments": "Ignore slow torrents.",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null
      },
      {
        "section": "Arr",
        "path": [
          "Torrent",
          "StalledDelay"
        ],
        "key": "Torrent.StalledDelay",
        "label": "Stalled Delay",
        "kind": "duration",
        "default": 15,
        "comments": "Stalled cleanup grace period in minutes (-1 = Infinite, 0 = immediate cleanup)",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null,
        "nativeUnit": "minutes",
        "allowNegative": true
      },
      {
        "section": "Arr",
        "path": [
          "Torrent",
          "ReSearchStalled"
        ],
        "key": "Torrent.ReSearchStalled",
        "label": "Re-Search Stalled",
        "kind": "checkbox",
        "default": false,
        "comments": "Re-search stalled torrents when StalledDelay is enabled and you want to re-search before removing the stalled torrent, or only after the torrent is removed.",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null
      },
      {
        "section": "Arr",
        "path": [
          "Torrent",
          "SeedingMode",
          "DownloadRateLimitPerTorrent"
        ],
        "key": "Torrent.SeedingMode.DownloadRateLimitPerTorrent",
        "label": "Download Rate Limit",
        "kind": "number",
        "default": -1,
        "comments": [
          "Set the maximum allowed download rate for torrents",
          "Set this value to -1 to disabled it",
          "Note that if you set the DownloadRateLimit on a tracker basis that value is favoured over this value"
        ],
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null,
        "allowNegative": true
      },
      {
        "section": "Arr",
        "path": [
          "Torrent",
          "SeedingMode",
          "UploadRateLimitPerTorrent"
        ],
        "key": "Torrent.SeedingMode.UploadRateLimitPerTorrent",
        "label": "Upload Rate Limit",
        "kind": "number",
        "default": -1,
        "comments": [
          "Set the maximum allowed upload rate for torrents",
          "Set this value to -1 to disabled it",
          "Note that if you set the UploadRateLimit on a tracker basis that value is favoured over this value"
        ],
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null,
        "allowNegative": true
      },
      {
        "section": "Arr",
        "path": [
          "Torrent",
          "SeedingMode",
          "MaxUploadRatio"
        ],
        "key": "Torrent.SeedingMode.MaxUploadRatio",
        "label": "Max Upload Ratio",
        "kind": "number",
        "default": -1,
        "comments": [
          "Set the maximum allowed upload ratio for torrents",
          "Set this value to -1 to disable it (no limit from this source)",
          "A positive tracker MaxUploadRatio overrides this value; tracker -1/unset does not clear this limit",
          "Unlimited only when neither SeedingMode nor a matched tracker sets a positive ratio limit"
        ],
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null,
        "allowNegative": true
      },
      {
        "section": "Arr",
        "path": [
          "Torrent",
          "SeedingMode",
          "MaxSeedingTime"
        ],
        "key": "Torrent.SeedingMode.MaxSeedingTime",
        "label": "Max Seeding Time",
        "kind": "duration",
        "default": -1,
        "comments": [
          "Set the maximum seeding time for torrents (seconds, or duration strings like \u00222w\u0022)",
          "Set this value to -1 to disable it (no limit from this source)",
          "A positive tracker MaxSeedingTime overrides this value; tracker -1/unset does not clear this limit",
          "Unlimited only when neither SeedingMode nor a matched tracker sets a positive time limit"
        ],
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null,
        "nativeUnit": "seconds",
        "allowNegative": true
      },
      {
        "section": "Arr",
        "path": [
          "Torrent",
          "SeedingMode",
          "RemoveTorrent"
        ],
        "key": "Torrent.SeedingMode.RemoveTorrent",
        "label": "Remove Torrent",
        "kind": "select",
        "default": -1,
        "comments": "Remove torrent condition (-1=Do not remove, 1=Remove on MaxUploadRatio, 2=Remove on MaxSeedingTime, 3=Remove on MaxUploadRatio or MaxSeedingTime, 4=Remove on MaxUploadRatio and MaxSeedingTime)",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null,
        "options": [
          "-1",
          "1",
          "2",
          "3",
          "4"
        ]
      },
      {
        "section": "Arr",
        "path": [
          "Torrent",
          "SeedingMode",
          "RemoveDeadTrackers"
        ],
        "key": "Torrent.SeedingMode.RemoveDeadTrackers",
        "label": "Remove Dead Trackers",
        "kind": "checkbox",
        "default": false,
        "comments": "Enable if you want to remove dead trackers",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null
      },
      {
        "section": "Arr",
        "path": [
          "Torrent",
          "SeedingMode",
          "RemoveTrackerWithMessage"
        ],
        "key": "Torrent.SeedingMode.RemoveTrackerWithMessage",
        "label": "Remove Tracker With Message",
        "kind": "tags",
        "default": [
          "skipping tracker announce (unreachable)",
          "No such host is known",
          "unsupported URL protocol",
          "info hash is not authorized with this tracker"
        ],
        "comments": "If \u0022RemoveDeadTrackers\u0022 is set to true then remove trackers with the following messages",
        "required": false,
        "secure": false,
        "uiExpose": true,
        "applyLive": null,
        "requiresRestart": null
      }
    ]
  }
} as const;

export type GeneratedConfigSchema = typeof CONFIG_SCHEMA;
export const CONFIG_SCHEMA_FIELD_COUNT = Object.values(CONFIG_SCHEMA.sections)
  .reduce((total, fields) => total + fields.length, 0);
