using System.Text.Json;
using Torrentarr.Core.Configuration;

var root = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "../../../../../"));
var outputPath = Path.Combine(root, "webui/src/config/configFields.generated.ts");
var json = JsonSerializer.Serialize(ConfigSchemaBuilder.Build(), new JsonSerializerOptions
{
    WriteIndented = true
});
var output = "// Generated by Torrentarr.ConfigSchemaGenerator. Do not edit.\n"
    + $"export const CONFIG_SCHEMA = {json} as const;\n\n"
    + "export type GeneratedConfigSchema = typeof CONFIG_SCHEMA;\n"
    + "export const CONFIG_SCHEMA_FIELD_COUNT = Object.values(CONFIG_SCHEMA.sections)\n"
    + "  .reduce((total, fields) => total + fields.length, 0);\n";

if (args.Contains("--check", StringComparer.Ordinal))
{
    if (!File.Exists(outputPath) || File.ReadAllText(outputPath) != output)
    {
        Console.Error.WriteLine($"Generated config schema is stale: {outputPath}");
        return 1;
    }

    Console.WriteLine("Generated config schema is current.");
    return 0;
}

Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
File.WriteAllText(outputPath, output);
Console.WriteLine($"Generated {outputPath}");
return 0;
